// Generated by stylus-bindgen
#![allow(clippy::all)]
use stylus_sdk::{alloy_primitives::{Address, U256}, alloy_sol_types::SolType, call::RawCall, prelude::*};

pub struct Contract {
    pub address: Address,
}

impl Contract {
    pub fn new(address: Address) -> Self { Self { address } }

    // Original: approve(address,uint256)
    pub fn approve__0x095ea7b3(&self, spender: Address, value: U256) -> Result<Vec<u8>, Vec<u8>> {
        let input = hex::decode("095ea7b3").unwrap();
        // note: real encoding requires SolType definitions (Milestone 2)
        let result = unsafe { RawCall::new_static().call(self.address, &input)? };
        Ok(result)
    }

    // Original: balanceOf(address)
    pub fn balance_of__0x70a08231(&self, owner: Address) -> Result<Vec<u8>, Vec<u8>> {
        let input = hex::decode("70a08231").unwrap();
        // note: real encoding requires SolType definitions (Milestone 2)
        let result = unsafe { RawCall::new_static().call(self.address, &input)? };
        Ok(result)
    }

    // Original: transfer(address,uint256)
    pub fn transfer__0xa9059cbb(&self, to: Address, value: U256) -> Result<Vec<u8>, Vec<u8>> {
        let input = hex::decode("a9059cbb").unwrap();
        // note: real encoding requires SolType definitions (Milestone 2)
        let result = unsafe { RawCall::new_static().call(self.address, &input)? };
        Ok(result)
    }
}
