// Generated by stylus-bindgen
#![allow(clippy::all)]
use stylus_sdk::{alloy_primitives::{Address, U256}, alloy_sol_types::SolType, call::RawCall, prelude::*};

pub struct Contract {
    pub address: Address,
}

impl Contract {
    pub fn new(address: Address) -> Self { Self { address } }

    // Original: supportsInterface(bytes4)
    pub fn supports_interface__0x01ffc9a7(&self, interfaceId: Vec<u8>) -> Result<Vec<u8>, Vec<u8>> {
        let input = hex::decode("01ffc9a7").unwrap();
        // note: real encoding requires SolType definitions (Milestone 2)
        let result = unsafe { RawCall::new_static().call(self.address, &input)? };
        Ok(result)
    }
}
